-- CreateEnum
CREATE TYPE "Plan" AS ENUM ('FREE', 'PRO', 'ENTERPRISE');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "maxFiles" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "maxTeams" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "plan" "Plan" NOT NULL DEFAULT 'FREE',
ADD COLUMN     "totalCreatedFiles" INTEGER NOT NULL DEFAULT 0;
